### ISSUE TITLE
[ASK] Pemakaian $regencies = $province->regencies;

### ISSUE THREAD

**Issue by baralogi** [azishapidin/indoregion#10]
Mas mau tanya bagaimana pemakaian
// Get Kabupaten/Kota dari sebuah Provinsi
$regencies = $province->regencies; untuk dijadikan dinamis combo box menggunakan ajax

**Comment by azishapidin** [comment]
Kirim terlebih dahulu ID provinsi yang dipilih, setelah itu munculkan list kabupaten/kota-nya. Contoh:
```
$province = \App\Models\Province::findOrFail(request()->province_id);

return response()->json($province->regencies);
```

Atau bisa juga:
```
$regencies = \App\Models\Regency::where('province_id', request()->province_id)->get();

return response()->json($regencies);
```
