### ISSUE TITLE
Warning Composer

### ISSUE THREAD

**Issue by azishapidin** [azishapidin/indoregion#12]
![4E4B564F-22E5-42F0-A0B3-C800B1C0B3C7](https://user-images.githubusercontent.com/20080537/80433723-de04bd00-8921-11ea-8ecb-1c75774a449f.png)

**Comment by cacing69** [comment]
perlu di struktur ulang kya nya ya mas

**Comment by cacing69** [comment]
perlu di sesuaikan struktur nya kya ny ya biar pake PSR-0 itu kan @azishapidin

**Comment by iamutaki** [comment]
perlu di ubah k PSR-4 kya nya ya mas @azishapidin

**Comment by azishapidin** [comment]
Fixed on version 2.2.2
