### ISSUE TITLE
error regency get by province

### ISSUE THREAD

**Issue by destiaarti** [azishapidin/indoregion#15]
// Get Kabupaten/Kota dari sebuah Provinsi
$regencies = $province->regencies;
 controller saya:
use App\Models\Province;
use App\Models\Regency;
use App\Models\District;
use App\Models\Village;
  public function regency($province)
    {
        $regencies =  $province->regencies;
        return response()->json($regencies);
    }
route saya:
Route::get('/regency/{province}','RegionController@regency');

hasil :
ErrorException: Trying to get property 'regencies' of non-object in ...

itu knp ya mas @azishapidin ? ada yg kurang kah, saya sudah sesuai github untuk instalasinya, saya pakai laravel 7.

**Comment by destiaarti** [comment]
uda solve mas, 
saya lihat dari https://github.com/azishapidin/indoregion/issues/10

**Comment by azishapidin** [comment]
Coba periksa $province nya pake dd($province)

**Comment by destiaarti** [comment]
uda solve ko mas hehe, trnyata hrs manggil model dulu . jadi bentuknya objek gitu.
sebelumnya saya kan manggilnya si id langsung, saya kira sama macam api lokasi rajaongkir. Jd parameternya langsung id gitu.
makasii mas hehehe
