### ISSUE TITLE
Laravel 8: Seeder, namespace dan Facades DB issue

### ISSUE THREAD

**Issue by fajarwz** [azishapidin/indoregion#16]
Halo bang, 

nice package.
Tapi saya ada masalah, disini saya menggunakan Laravel 8. Ketika `php artisan indoregion:publish` dijalankan, Seeder tidak otomatis tercopy ke folder seeders saya (akhirnya saya copy manual). Lalu di seeder tidak ter-include otomatis namespace `namespace Database\Seeders` dan `use Illuminate\Support\Facades\DB` (akhirnya saya masukkan manual juga).

setelah diperbaiki dengan dimasukkan manual alhamdulillah data seeder bisa muncul bang.

apakah ini bug atau ada hal yang saya lewatkan?

Terimakasih.

**Comment by kharizma** [comment]
seperti nya karena blm support untuk Laravel versi 8

**Comment by kharizma** [comment]
> Halo bang,
> 
> nice package.
> Tapi saya ada masalah, disini saya menggunakan Laravel 8. Ketika `php artisan indoregion:publish` dijalankan, Seeder tidak otomatis tercopy ke folder seeders saya (akhirnya saya copy manual). Lalu di seeder tidak ter-include otomatis namespace `namespace Database\Seeders` dan `use Illuminate\Support\Facades\DB` (akhirnya saya masukkan manual juga).
> 
> setelah diperbaiki dengan dimasukkan manual alhamdulillah data seeder bisa muncul bang.
> 
> apakah ini bug atau ada hal yang saya lewatkan?
> 
> Terimakasih.

Sepertinya karena blm support untuk Laravel versi 8 yang masih terbilang baru ....

**Comment by azishapidin** [comment]
Cek versi terbaru ya 🔥
