### ISSUE TITLE
error  indoregion:publish Laravel 7

### ISSUE THREAD

**Issue by riswanardinatahub** [azishapidin/indoregion#18]
C:\laragon\www\desaku
λ php artisan indoregion:publish
Copying file: C:\laragon\www\desaku\app/Models/District.php
Copying file: C:\laragon\www\desaku\app/Models/Province.php
Copying file: C:\laragon\www\desaku\app/Models/Regency.php
Copying file: C:\laragon\www\desaku\app/Models/Village.php
Copying file: C:\laragon\www\desaku\database/migrations/2017_05_02_140432_create_provinces_tables.php
Copying file: C:\laragon\www\desaku\database/migrations/2017_05_02_140444_create_regencies_tables.php
Copying file: C:\laragon\www\desaku\database/migrations/2017_05_02_142019_create_districts_tables.php
Copying file: C:\laragon\www\desaku\database/migrations/2017_05_02_143454_create_villages_tables.php
Copying file: C:\laragon\www\desaku\database/seeders/IndoRegionDistrictSeeder.php

   ErrorException

  copy(C:\laragon\www\desaku\database/seeders/IndoRegionDistrictSeeder.php): failed to open stream: No such file or directory

  at C:\laragon\www\desaku\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:252
    248|      * @return bool
    249|      */
    250|     public function copy($path, $target)
    251|     {
  > 252|         return copy($path, $target);
    253|     }
    254|
    255|     /**
    256|      * Create a symlink to the target file or directory. On Windows, a hard link is created if the target is a file.

  1   C:\laragon\www\desaku\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:252
      copy("C:\laragon\www\desaku\vendor\azishapidin\indoregion\src/database/seeders/IndoRegionDistrictSeeder.php", "C:\laragon\www\desaku\database/seeders/IndoRegionDistrictSeeder.php")

  2   C:\laragon\www\desaku\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
      Illuminate\Filesystem\Filesystem::copy("C:\laragon\www\desaku\vendor\azishapidin\indoregion\src/database/seeders/IndoRegionDistrictSeeder.php", "C:\laragon\www\desaku\database/seeders/IndoRegionDistrictSeeder.php")

**Comment by joyonurdiansyah** [comment]
sudah solved kah mas, saya punya error yang sama
