### ISSUE TITLE
DB Seed ErrorException

### ISSUE THREAD

**Issue by dwiriyant** [azishapidin/indoregion#19]
Got this error when run db:seed on laravel 8.37

 ```
ErrorException 

  Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead.

  at vendor/parsecsv/php-parsecsv/src/Csv.php:406
    402▕             trigger_error(
    403▕                 'Supplying file paths to parse() will no longer ' .
    404▕                 'be supported in a future version of ParseCsv. ' .
    405▕                 'Use ->parseFile() instead.',
  ➜ 406▕                 E_USER_DEPRECATED
    407▕             );
    408▕         } else {
    409▕             $this->file = null;
    410▕             $this->file_data = &$dataString;

      +4 vendor frames 
  5   database/seeders/IndoRegionProvinceSeeder.php:27
      AzisHapidin\IndoRegion\RawDataGetter::getProvinces()

      +7 vendor frames 
  13  database/seeders/IndoRegionSeeder.php:23
      Illuminate\Database\Seeder::call("Database\Seeders\IndoRegionProvinceSeeder")
```

**Comment by dwiriyant** [comment]
Sorry, i will re-investigate this

**Comment by maulana-reza** [comment]
same issue, here for solve this issue
  change ``$this->parse($data);`` to ``$this->parseFile($data);`` on line ``vendor/parsecsv/php-parsecsv/src/Csv.php:333``

**Comment by ganyuciha** [comment]
Mas @azishapidin please help check

**Comment by azishapidin** [comment]
Thanks for report, i will check this issue ASAP

**Comment by azishapidin** [comment]
Sudah fix ya, silahkan install versi terbaru (3.0.3)

Terima kasih @amyisme13 @maulana-reza @ganyuciha

**Comment by adammico122** [comment]
sama di laravel 7.

**Comment by adammico122** [comment]
php artisan db:seed --class=IndoRegionProvinceSeeder

   ErrorException

  Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead.

  at C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:406
    402|             trigger_error(
    403|                 'Supplying file paths to parse() will no longer ' .
    404|                 'be supported in a future version of ParseCsv. ' .
    405|                 'Use ->parseFile() instead.',
  > 406|                 E_USER_DEPRECATED
    407|             );
    408|         } else {
    409|             $this->file = null;
    410|             $this->file_data = &$dataString;

  1   C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:406
      trigger_error("Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead.")

  2   C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:333
      ParseCsv\Csv::parse("C:\laragon\www\bwa-adam\vendor\azishapidin\indoregion\src/data/csv/provinces.csv")

**Comment by azishapidin** [comment]
> php artisan db:seed --class=IndoRegionProvinceSeeder
> 
> ErrorException
> 
> Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead.
> 
> at C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:406
> 402| trigger_error(
> 403| 'Supplying file paths to parse() will no longer ' .
> 404| 'be supported in a future version of ParseCsv. ' .
> 405| 'Use ->parseFile() instead.',
> 
> > 406|                 E_USER_DEPRECATED
> > 407|             );
> > 408|         } else {
> > 409|             $this->file = null;
> > 410|             $this->file_data = &$dataString;
> 
> 1 C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:406
> trigger_error("Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead.")
> 
> 2 C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:333
> ParseCsv\Csv::parse("C:\laragon\www\bwa-adam\vendor\azishapidin\indoregion\src/data/csv/provinces.csv")

Sudah install versi terbaru?

**Comment by azishapidin** [comment]
@adammico122 silahkan cek dokumentasi instalasi yang baru

**Comment by kodekita-tech** [comment]
di laravel 6 juga eror. udah jalanin composer dump-autoload. udah jalanin php artisan db:seed --class=IndoRegionSeeder

**Comment by azishapidin** [comment]
> di laravel 6 juga eror. udah jalanin composer dump-autoload. udah jalanin php artisan db:seed --class=IndoRegionSeeder

@mrijalul itu pake versi package yang mana? FYI untuk Laravel 6 hanya support sampai versi 2.2.2
composer require azishapidin/indoregion:2.2.2

**Comment by vandyahmad24** [comment]
klo project laravel saya v6 installnya azishapidin/indoregion:2.2.2  trus dapet error  Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead., hrusnya bagaimana ya?

**Comment by amyisme13** [comment]
> klo project laravel saya v6 installnya azishapidin/indoregion:2.2.2 trus dapet error Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead., hrusnya bagaimana ya?

Untuk laravel 6 & 7 bisa difix dengan membatasi versi parsecsvnya ke 1.2 karena deprecation notice baru muncul di versi 1.3.
Caranya:
`composer require parsecsv/php-parsecsv:1.2`

**Comment by mrijalul** [comment]
@amyisme13 thanks, bisa mas

**Comment by kodekita-tech** [comment]
> > klo project laravel saya v6 installnya azishapidin/indoregion:2.2.2 trus dapet error Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead., hrusnya bagaimana ya?
> 
> Untuk laravel 6 & 7 bisa difix dengan membatasi versi parsecsvnya ke 1.2 karena deprecation notice baru muncul di versi 1.3.
> Caranya:
> `composer require parsecsv/php-parsecsv:1.2`

@amyisme13 bisa mas

**Comment by aldhytrisnaldi** [comment]
> composer require parsecsv/php-parsecsv:1.2

thx for info mas

**Comment by azkiya12** [comment]
> 

ok fix dengan cara ini
