### ISSUE TITLE
 Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead. On Laravel 7

### ISSUE THREAD

**Issue by adammico122** [azishapidin/indoregion#21]
php artisan db:seed --class=IndoRegionSeeder
Seeding: IndoRegionProvinceSeeder

   ErrorException

  Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead.

  at C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:406
    402|             trigger_error(
    403|                 'Supplying file paths to parse() will no longer ' .
    404|                 'be supported in a future version of ParseCsv. ' .
    405|                 'Use ->parseFile() instead.',
  > 406|                 E_USER_DEPRECATED
    407|             );
    408|         } else {
    409|             $this->file = null;
    410|             $this->file_data = &$dataString;

  1   C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:406
      trigger_error("Supplying file paths to parse() will no longer be supported in a future version of ParseCsv. Use ->parseFile() instead.")

  2   C:\laragon\www\bwa-adam\vendor\parsecsv\php-parsecsv\src\Csv.php:333
      ParseCsv\Csv::parse("C:\laragon\www\bwa-adam\vendor\azishapidin\indoregion\src/data/csv/provinces.csv")

**Comment by azishapidin** [comment]
@adammico122 sudah install versi terbaru?

**Comment by azishapidin** [comment]
@adammico122 Sudah cek dokumentasi instalasi terbaru?
