### ISSUE TITLE
Install di lumen 5.8

### ISSUE THREAD

**Issue by k1m0ch1** [azishapidin/indoregion#5]
Hi, kayanya ada masalah kalo install di lumen 5.8
ga bisa php vendor:publish sama sekali,
ada saran ?

**Comment by iamutaki** [comment]
sebenarnya kalo pengen cepatnya bisa dicopy manual dari vendor nya mas, 

tapi saya coba buat Pull Request nya , utk publish di lumen @k1m0ch1

**Comment by iamutaki** [comment]
saya baru buat pull requestnya @k1m0ch1  untuk publish file Model, Migration & Seed nya. mas, nantu kalo udah di merge dan ada masalah kita diskusi lagi ya

**Comment by azishapidin** [comment]
@cacing69 saya coba cek pull request nya ya

**Comment by iamutaki** [comment]
iya mas, saya barusan nyoba nya di lumen 5.8 aja pas buat kemaren @azishapidin

**Comment by azishapidin** [comment]
@cacing69 @k1m0ch1 sekarang udah saya update ya jadi versi 2.2.0, udah saya cek di Laravel 6.x, Lumen 6.x, dan Laravel 5.4 masih aman.

**Comment by iamutaki** [comment]
ohh baguslah kalo begitu mas @cacing69

**Comment by k1m0ch1** [comment]
nuhun sadayana!

**Comment by iamutaki** [comment]
sama sama mas @k1m0ch1
