### ISSUE TITLE
[ASK] Base Model dan Facade

### ISSUE THREAD

**Issue by iamutaki** [azishapidin/indoregion#8]
apakah perlu di package ini dibuatkan Facade dan dibuatkan BaseModel yang nantinya akan lebih mudah untuk di maintenance ketika melakukan penambahan method dan melakukan test?

**Comment by azishapidin** [comment]
@cacing69 Ide bagus, saya juga kepikiran buat buat Facade. Agar lebih enak juga di pemakaiannya

**Comment by iamutaki** [comment]
kira kira facade nya di gabung utk handling semua kelas ya mas. dan nama nya apa ya, kalo ada waktu luang nnti saya buatin
dengan ini juga, kayak nya kelas nya bisa dibuat base, biar nnti model yg ada di App/Model/ extends nya ke kelas base IndoRegion

```
namespace App\Model;

use IndoRegion\Models\IndoRegionProvince
class Province extends IndoRegionProvince
```

**Comment by azishapidin** [comment]
Siap ditunggu mas
